# Generated by Django 5.1.4 on 2024-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.FloatField(default=0.0, verbose_name='Original Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL'), (6, '28'), (7, '30'), (8, '32')], verbose_name='Size'),
        ),
    ]
