# Generated by Django 5.1.4 on 2024-12-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0002_product_original_price_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, 'Top Wear'), (2, 'Bottom Wear')], default=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'T-Shirts'), (2, 'Shirts'), (3, 'Jeans'), (4, 'Trousers'), (5, 'Boxers'), (6, 'Polo T-shirt'), (7, 'OverSized T-shirt')], verbose_name='Product Category'),
        ),
    ]
