# Generated by Django 5.1.4 on 2025-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='current_status',
            field=models.CharField(default='Order Placed', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
