# Generated by Django 5.1.4 on 2025-01-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0006_orders_is_cancelled_alter_orders_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'OrderPlaced'), (2, 'Shipped'), (3, 'Out for Delivery'), (4, 'Delivered')], verbose_name='Order Status'),
        ),
    ]
