# Generated by Django 5.1.4 on 2025-01-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0008_alter_orders_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='current_status',
            field=models.CharField(default='Order Placed', max_length=100),
        ),
    ]
