# Generated by Django 5.1.4 on 2025-01-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0009_alter_address_phone_alter_orders_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
