# Generated by Django 5.1.4 on 2025-01-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0010_alter_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
