# Generated by Django 5.1.4 on 2025-01-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0012_shippingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
