# Generated by Django 5.1.4 on 2025-01-26 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0013_alter_shippingdetail_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='shipping_details', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
