# Generated by Django 5.1.4 on 2025-01-26 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0016_alter_shippingdetail_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetail',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
