# Generated by Django 5.1.4 on 2025-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0017_remove_shippingdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
