# Generated by Django 5.1.4 on 2025-01-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0018_shippingdetail_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetail',
            name='is_selected',
        ),
    ]
