# Generated by Django 5.1.4 on 2025-01-26 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0019_remove_shippingdetail_is_selected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='current_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Placed', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
