# Generated by Django 5.1.4 on 2025-01-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0020_alter_orders_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='Created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
