# Generated by Django 5.1.4 on 2025-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0021_shippingdetail_created_at_shippingdetail_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
