# Generated by Django 5.1.4 on 2025-01-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0022_alter_shippingdetail_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='current_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Dispatched', 'Dispatched'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Placed', max_length=100),
        ),
    ]
