# Generated by Django 5.1.2 on 2025-07-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0024_orders_created_at_orders_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
